# Generated by Django 3.0.7 on 2020-06-09 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='user', max_length=255)),
                ('name', models.CharField(default='name', max_length=255)),
                ('category', models.CharField(default='category', max_length=255)),
                ('welcomeOne', models.CharField(default='welcomeOne', max_length=255)),
                ('welcomeOneDes', models.CharField(default='welcomeTwo', max_length=255)),
                ('welcomeTwoDes', models.CharField(default='welcomeTwoDes', max_length=255)),
                ('about', models.CharField(default='about', max_length=555)),
                ('galleryDes', models.CharField(default='galleryDes', max_length=255)),
                ('phone', models.CharField(default='phone', max_length=255)),
                ('email', models.EmailField(default='admin@admin.com', max_length=255)),
                ('location', models.CharField(default='location', max_length=255)),
                ('aboutFooter', models.CharField(default='aboutFooter', max_length=255)),
                ('openingHours', models.CharField(default='openingHours', max_length=255)),
                ('fbLink', models.CharField(default='fbLink', max_length=255)),
                ('instaLink', models.CharField(default='instaLink', max_length=255)),
                ('youtubeLink', models.CharField(default='youtubeLink', max_length=255)),
                ('backgroundColor', models.CharField(default='backgroundColor', max_length=255)),
                ('photo_1', models.ImageField(default='', upload_to='%y/%m/%d')),
                ('photo_2', models.ImageField(default='', upload_to='%y/%m/%d')),
                ('photo_3', models.ImageField(default='', upload_to='%y/%m/%d')),
                ('photo_4', models.ImageField(default='', upload_to='%y/%m/%d')),
                ('photo_5', models.ImageField(default='', upload_to='%y/%m/%d')),
                ('photo_6', models.ImageField(default='', upload_to='%y/%m/%d')),
                ('photo_7', models.ImageField(default='', upload_to='%y/%m/%d')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MetaWebFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PaidUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfSiteH', models.CharField(default='NameOfSite', max_length=255)),
                ('category', models.CharField(default='category', max_length=255)),
                ('headingOneH', models.CharField(default='heading One', max_length=255)),
                ('descriptionOneH', models.CharField(default='description one', max_length=255)),
                ('headingTwoH', models.CharField(default='Heading Two', max_length=255)),
                ('descriptionTwoH', models.CharField(default='description two', max_length=255)),
                ('headingThreeH', models.CharField(default='heading three', max_length=255)),
                ('descriptionThreeH', models.CharField(default='description three', max_length=255)),
                ('featureOneH', models.CharField(default='feature One', max_length=255)),
                ('featureOneDesH', models.CharField(default='feature description one', max_length=255)),
                ('featureTwoH', models.CharField(default='feature Two', max_length=255)),
                ('featureTwoDesH', models.CharField(default='feature description two', max_length=255)),
                ('featureThreeH', models.CharField(default='feature three', max_length=255)),
                ('featureThreeDesH', models.CharField(default='feature description three', max_length=255)),
                ('introductionA', models.CharField(default='introduction', max_length=255)),
                ('whatWeDoA', models.CharField(default='what we do', max_length=255)),
                ('titleC', models.CharField(default='title', max_length=255)),
                ('emailC', models.EmailField(max_length=255)),
                ('descriptionC', models.CharField(default='description', max_length=255)),
                ('phoneC', models.CharField(max_length=255)),
                ('addressC', models.CharField(default='address', max_length=255)),
                ('serviceOne', models.CharField(default='Service One', max_length=255)),
                ('serviceOneDes', models.CharField(default='description of service one', max_length=255)),
                ('serviceTwo', models.CharField(default='Service Two', max_length=255)),
                ('serviceTwoDes', models.CharField(default='description of service two', max_length=255)),
                ('serviceThree', models.CharField(default='Service Three', max_length=255)),
                ('serviceThreeDes', models.CharField(default='description of service three', max_length=255)),
                ('backgroundColor', models.CharField(default='backgroundColor', max_length=255)),
                ('user', models.CharField(default='user', max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=250)),
                ('shopId', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Website')),
            ],
        ),
    ]
