# Generated by Django 3.0.5 on 2020-06-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='MetaWebFeedback',
        ),
        migrations.DeleteModel(
            name='PaidUser',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
